kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
  - protocol: TCP
    port: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
      matchLabels:
        app: backend
        tier: backend
  replicas: 1 
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: anthony2801/backend:latest
          ports:
            - containerPort: 8081
