---

kind: Deployment
#commento

apiVersion: extensions/v1beta1

metadata:

  name: kafka-broker0

spec:
  replicas: 1

  template:

    metadata:

      labels:

        app: kafka

        id: "0"

    spec:

      containers:

      - name: kafka

        image: wurstmeister/kafka

        ports:

        - containerPort: 9092

        env:

        - name: KAFKA_ADVERTISED_PORT

          value: "9092"

        - name: KAFKA_ADVERTISED_HOST_NAME

          value: a1dfd95cadc6111e8beda0a565ef478c-145970444.us-west-2.elb.amazonaws.com

        - name: KAFKA_ZOOKEEPER_CONNECT

          value: zoo1:2181

        - name: KAFKA_BROKER_ID

          value: "0"

        - name: KAFKA_CREATE_TOPICS

          value: topic1:1:1

#sostituire il valore di KAFKA_ADVERTISED_HOST_NAME con quello dell'ip/hostname del load balancer di kafka
