apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: clients
      port: 2181
      targetPort: 2181
    - name: peers
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper
